In [ ]:
import torch

In [30]:
a = torch.tensor([[1,1,0,0],[1,1,1,0]])
a

tensor([[1, 1, 0, 0],
        [1, 1, 1, 0]])

In [54]:
c = a.repeat_interleave(a.size(-1),dim=1)
c

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])

In [52]:
c.shape

torch.Size([8, 4])

In [53]:
b = a.repeat_interleave(a.size(-1),dim=1).reshape(2,4,4)
b

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0]]])

In [27]:
b.shape

torch.Size([2, 3, 3])

In [10]:
help(a.repeat_interleave)

Help on built-in function repeat_interleave:

repeat_interleave(...) method of torch.Tensor instance
    repeat_interleave(repeats, dim=None, *, output_size=None) -> Tensor
    
    See :func:`torch.repeat_interleave`.



In [9]:
help(a.repeat)

Help on built-in function repeat:

repeat(...) method of torch.Tensor instance
    repeat(*repeats) -> Tensor
    
    Repeats this tensor along the specified dimensions.
    
    Unlike :meth:`~Tensor.expand`, this function copies the tensor's data.
    
    .. warning::
    
        :meth:`~Tensor.repeat` behaves differently from
        `numpy.repeat <https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html>`_,
        but is more similar to
        `numpy.tile <https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html>`_.
        For the operator similar to `numpy.repeat`, see :func:`torch.repeat_interleave`.
    
    Args:
        repeat (torch.Size, int..., tuple of int or list of int): The number of times to repeat this tensor along each dimension
    
    Example::
    
        >>> x = torch.tensor([1, 2, 3])
        >>> x.repeat(4, 2)
        tensor([[ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2

In [55]:
-torch.exp(torch.tensor(8))

tensor(-2980.9580)

In [67]:
x.size()

torch.Size([3, 2])

In [34]:
input = torch.tensor([[1,7,3,8],[1,7,3,8]])
input = input.repeat_interleave(input.size(-1), dim=0).reshape(input.size(0), input.size(1), -1)
input.shape


torch.Size([2, 4, 4])

In [30]:
x_bool = (x == 0) 
x_bool

tensor([[[False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True]],

        [[False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True]]])

In [29]:
~x

tensor([[[-2, -2, -1, -1],
         [-2, -2, -1, -1],
         [-2, -2, -1, -1],
         [-2, -2, -1, -1]],

        [[-2, -2, -2, -1],
         [-2, -2, -2, -1],
         [-2, -2, -2, -1],
         [-2, -2, -2, -1]]])

In [32]:
x

tensor([[[False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True]],

        [[False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True]]])

In [35]:
x = torch.tensor([[1,1,0,0],[1,1,1,0]])
print(x.size())
print(x)
x = x.repeat_interleave(x.size(-1), dim=0).reshape(x.size(0), x.size(1), -1)
# x = x.unsqueeze(1).expand(2,4,4)
print(x.size())
print(x)
print(x[1])
# print(x)
# x = (x==0)
input[x==0] = 88
print(input)

torch.Size([2, 4])
tensor([[1, 1, 0, 0],
        [1, 1, 1, 0]])
torch.Size([2, 4, 4])
tensor([[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0]],

        [[1, 1, 1, 0],
         [1, 1, 1, 0],
         [1, 1, 1, 0],
         [1, 1, 1, 0]]])
tensor([[1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0]])
tensor([[[ 1,  7, 88, 88],
         [ 1,  7, 88, 88],
         [ 1,  7, 88, 88],
         [ 1,  7, 88, 88]],

        [[ 1,  7,  3, 88],
         [ 1,  7,  3, 88],
         [ 1,  7,  3, 88],
         [ 1,  7,  3, 88]]])


In [19]:
import torch

# 原始张量
tensor = torch.tensor([[1, 1, 0], [1, 0, 0]])

# 扩展为三维张量
# expanded_tensor = tensor.unsqueeze(2).expand(2,3,4)  # 在第三维重复
br = torch.tensor([[0],[1]])
br = br==1

print(tensor)

print(br)
print(br.shape)


tensor([[1, 1, 0],
        [1, 0, 0]])
tensor([[False],
        [ True]])
torch.Size([2, 1])


In [21]:
tensor.masked_fill_(br,88)

tensor([[ 1,  1,  0],
        [88, 88, 88]])

In [11]:
import torch
import torch.nn as nn
m = nn.Dropout(p=0.2)
input = torch.randn(4, 3)
output = m(input)
print(input)
print(output)
output = m(input)
print(input)
print(output)

tensor([[-0.8798, -1.1283, -0.2033],
        [-0.1010,  0.7691,  0.5724],
        [-0.7805,  0.8530, -0.0343],
        [ 1.3946,  2.0701, -0.6976]])
tensor([[-0.0000, -1.4104, -0.0000],
        [-0.1262,  0.9614,  0.7154],
        [-0.9756,  1.0662, -0.0429],
        [ 0.0000,  2.5877, -0.0000]])
tensor([[-0.8798, -1.1283, -0.2033],
        [-0.1010,  0.7691,  0.5724],
        [-0.7805,  0.8530, -0.0343],
        [ 1.3946,  2.0701, -0.6976]])
tensor([[-1.0998, -0.0000, -0.2542],
        [-0.1262,  0.9614,  0.7154],
        [-0.9756,  1.0662, -0.0429],
        [ 1.7432,  2.5877, -0.0000]])


In [22]:
import torch
logits = torch.randn(12, 10)  # 随机生成 logits
target = torch.randint(0, 10, (12,))  # 随机生成标签
import torch.nn as nn

criterion = nn.CrossEntropyLoss(reduction = "none")
loss = criterion(logits, target)  # 输出标量
print(loss)

tensor([2.7528, 2.5153, 1.5930, 3.3648, 2.6590, 4.4445, 1.6726, 3.3772, 2.4977,
        1.6535, 3.0751, 2.8612])


In [26]:
import torch
from torch import nn
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12,batch_first=True)
src = torch.rand((32,100, 512))
tgt = torch.rand((32,100, 512))
out = transformer_model(src, tgt)
print(out.shape)

torch.Size([32, 100, 512])


In [ ]:
%time
import torch
a = torch.randn((3000,3000))
b = torch.randn((3000,3000))
print((a@b)[0:3,0:3])

CPU times: user 7 μs, sys: 0 ns, total: 7 μs
Wall time: 14.3 μs
