In [ ]:
import torch

In [30]:
a = torch.tensor([[1,1,0,0],[1,1,1,0]])
a

tensor([[1, 1, 0, 0],
        [1, 1, 1, 0]])

In [54]:
c = a.repeat_interleave(a.size(-1),dim=1)
c

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]])

In [52]:
c.shape

torch.Size([8, 4])

In [53]:
b = a.repeat_interleave(a.size(-1),dim=1).reshape(2,4,4)
b

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0]]])

In [27]:
b.shape

torch.Size([2, 3, 3])

In [10]:
help(a.repeat_interleave)

Help on built-in function repeat_interleave:

repeat_interleave(...) method of torch.Tensor instance
    repeat_interleave(repeats, dim=None, *, output_size=None) -> Tensor
    
    See :func:`torch.repeat_interleave`.



In [9]:
help(a.repeat)

Help on built-in function repeat:

repeat(...) method of torch.Tensor instance
    repeat(*repeats) -> Tensor
    
    Repeats this tensor along the specified dimensions.
    
    Unlike :meth:`~Tensor.expand`, this function copies the tensor's data.
    
    .. warning::
    
        :meth:`~Tensor.repeat` behaves differently from
        `numpy.repeat <https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html>`_,
        but is more similar to
        `numpy.tile <https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html>`_.
        For the operator similar to `numpy.repeat`, see :func:`torch.repeat_interleave`.
    
    Args:
        repeat (torch.Size, int..., tuple of int or list of int): The number of times to repeat this tensor along each dimension
    
    Example::
    
        >>> x = torch.tensor([1, 2, 3])
        >>> x.repeat(4, 2)
        tensor([[ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2,  3],
                [ 1,  2,  3,  1,  2

In [55]:
-torch.exp(torch.tensor(8))

tensor(-2980.9580)

In [67]:
x.size()

torch.Size([3, 2])

In [34]:
input = torch.tensor([[1,7,3,8],[1,7,3,8]])
input = input.repeat_interleave(input.size(-1), dim=0).reshape(input.size(0), input.size(1), -1)
input.shape


torch.Size([2, 4, 4])

In [30]:
x_bool = (x == 0) 
x_bool

tensor([[[False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True]],

        [[False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True]]])

In [29]:
~x

tensor([[[-2, -2, -1, -1],
         [-2, -2, -1, -1],
         [-2, -2, -1, -1],
         [-2, -2, -1, -1]],

        [[-2, -2, -2, -1],
         [-2, -2, -2, -1],
         [-2, -2, -2, -1],
         [-2, -2, -2, -1]]])

In [32]:
x

tensor([[[False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True],
         [False, False,  True,  True]],

        [[False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True],
         [False, False, False,  True]]])

In [35]:
x = torch.tensor([[1,1,0,0],[1,1,1,0]])
print(x.size())
print(x)
x = x.repeat_interleave(x.size(-1), dim=0).reshape(x.size(0), x.size(1), -1)
# x = x.unsqueeze(1).expand(2,4,4)
print(x.size())
print(x)
print(x[1])
# print(x)
# x = (x==0)
input[x==0] = 88
print(input)

torch.Size([2, 4])
tensor([[1, 1, 0, 0],
        [1, 1, 1, 0]])
torch.Size([2, 4, 4])
tensor([[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0]],

        [[1, 1, 1, 0],
         [1, 1, 1, 0],
         [1, 1, 1, 0],
         [1, 1, 1, 0]]])
tensor([[1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 0]])
tensor([[[ 1,  7, 88, 88],
         [ 1,  7, 88, 88],
         [ 1,  7, 88, 88],
         [ 1,  7, 88, 88]],

        [[ 1,  7,  3, 88],
         [ 1,  7,  3, 88],
         [ 1,  7,  3, 88],
         [ 1,  7,  3, 88]]])


In [42]:
import torch

# 原始张量
tensor = torch.tensor([[1, 1, 0], [1, 0, 0]])

# 扩展为三维张量
expanded_tensor = tensor.unsqueeze(2).expand(2,3,4)  # 在第三维重复

print(tensor)

print(expanded_tensor)


tensor([[1, 1, 0],
        [1, 0, 0]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0]],

        [[1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])


In [44]:
expanded_tensor[0][1]

tensor([1, 1, 1, 1])